//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int PKID { get; set; }
        public Nullable<int> FK_MessageID { get; set; }
        public string Sender { get; set; }
        public string Message { get; set; }
        public string Files { get; set; }
        public Nullable<System.DateTime> RecordedDate { get; set; }
    }
}
