//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookers
    {
        public int PKID { get; set; }
        public string FKCompanyID { get; set; }
        public string HotelGroupCode { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> RecorderDate { get; set; } = DateTime.Now;
        public string RecorderUser { get; set; }
        public Nullable<System.DateTime> ModifierDate { get; set; }
        public string ModifierUser { get; set; }
        public string Role { get; set; }
        public string AgencyName { get; set; }
        public string AgencyEmail { get; set; }
        public string AgencyWebAddress { get; set; }
        public string AgencyAddress { get; set; }
        public string AgencyPhone { get; set; }
        public string AgencyLicence { get; set; }
        public string AgencyOwner { get; set; }
        public string AgencyZipCode { get; set; }
        public string AgencyCity { get; set; }
        public string AgencyCountry { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> ConfirmKVVK { get; set; }
    }
}
