//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        public int PKID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> Active { get; set; }
        public string FKCommunityID { get; set; }
        public string Email { get; set; }
        public string WebAddress { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonPhone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public Nullable<System.DateTime> RecorderDate { get; set; }
        public string RecorderUser { get; set; }
        public Nullable<System.DateTime> ModifierDate { get; set; }
        public string ModifierUser { get; set; }
        public string LicenceNumber { get; set; }
        public string OwnerName { get; set; }
    }
}
