//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public int PKID { get; set; }
        public string country_2_digit { get; set; }
        public string country_3_digit { get; set; }
        public Nullable<int> country_numeric_code { get; set; }
        public string ui_language { get; set; }
        public string Name_English { get; set; }
        public string Name_Turkce { get; set; }
    }
}
