//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRooms
    {
        public int PKID { get; set; }
        public Nullable<int> FKHotelID { get; set; }
        public string RoomName { get; set; }
        public string Description { get; set; }
        public string Images { get; set; }
        public string OperatorRoomCode { get; set; }
        public string PMSRoomCode { get; set; }
        public Nullable<decimal> RoomBonus { get; set; }
        public Nullable<System.DateTime> RecorderDate { get; set; }
        public string RecorderUser { get; set; }
        public Nullable<System.DateTime> ModifierDate { get; set; }
        public string ModifierUser { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> BookeraVerilebilir { get; set; }
        public Nullable<int> MaxAdult { get; set; }
        public Nullable<int> MaxChild { get; set; }
        public Nullable<int> MaxInfant { get; set; }
    }
}
