//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcı_Giris
    {
        public int ıd { get; set; }
        public string kullanıcıAd { get; set; }
        public string sifre { get; set; }
    }
}
