//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int PKID { get; set; }
        public Nullable<int> FK_ReservationID { get; set; }
        public Nullable<int> FK_HotelID { get; set; }
        public string Sender { get; set; }
        public string Reciever { get; set; }
        public string Message { get; set; }
        public string Files { get; set; }
        public string ilgili { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
