//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int PKID { get; set; }
        public Nullable<int> FKCompanyID { get; set; }
        public Nullable<int> FKBookerID { get; set; }
        public Nullable<int> FKHotelID { get; set; }
        public Nullable<int> FKOperatorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<int> RoomCount { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public int ReservationStatus { get; set; }
        public Nullable<System.DateTime> RecorderDate { get; set; }
        public string RecorderUser { get; set; }
        public Nullable<System.DateTime> ModifierDate { get; set; }
        public string ModifierUser { get; set; }
        public Nullable<decimal> TotalPoints { get; set; }
        public string Notes { get; set; }
        public decimal TotalPromotionPoints { get; set; }
        public Nullable<decimal> ExtraPayment { get; set; }
    }
}
