//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationRooms
    {
        public int PKID { get; set; }
        public Nullable<int> FKReservationID { get; set; }
        public Nullable<int> FKHotelID { get; set; }
        public Nullable<int> FKHotelRoomID { get; set; }
        public Nullable<int> AdultCount { get; set; }
        public Nullable<int> ChildCount { get; set; }
        public Nullable<int> InfantCount { get; set; }
        public Nullable<decimal> BonusPoints { get; set; }
        public Nullable<System.DateTime> RecorderDate { get; set; }
        public string RecorderUser { get; set; }
        public Nullable<System.DateTime> ModifierDate { get; set; }
        public string ModifierUser { get; set; }
        public Nullable<int> RoomStatus { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public decimal PromotionPoints { get; set; }
        public int RoomCount { get; set; }
        public Nullable<int> ServiceResult { get; set; }
        public Nullable<System.DateTime> StatusUpdateDate { get; set; }
        public Nullable<bool> MatchByName { get; set; }
        public Nullable<int> MaxAdult { get; set; }
        public Nullable<int> MaxChild { get; set; }
        public Nullable<int> MaxInfant { get; set; }
    }
}
